import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM, VirtualConsole } from 'jsdom';

test('构建后的 Content Script：无限滚动、事件操作、重绘、关闭与无观察器循环',async t => {
  const errors = [];
  const console = new VirtualConsole(); console.on('jsdomError',e => errors.push(e)); console.on('error',e => errors.push(e));
  const dom = new JSDOM('<main data-testid="primaryColumn"></main>', {url:'https://x.com/home',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:console});
  t.after(() => dom.window.close());
  const w = dom.window; let refresh;
  w.setInterval = callback => { refresh = callback; return 1; };
  w.clearInterval = () => {};
  let feed = {notes:Array.from({length:3},(_,i) => ({id:String(i).repeat(64),title:`笔记 ${i}`,html:'<p>正文</p><script>window.attacked=true</script><img src="https://evil/track">'})),settings:{every:10,enabled:true}};
  w.chrome = {runtime:{id:'test-extension',onMessage:{addListener:()=>{},removeListener:()=>{}},getURL:path=>`chrome-extension://test-extension${path}`,sendMessage:async () => feed}};
  let callbacks = 0;
  const Observer = w.MutationObserver;
  w.MutationObserver = class extends Observer { constructor(fn) { super((...args) => {callbacks++;fn(...args);}); } };
  const roots = new WeakMap(); const attach = w.Element.prototype.attachShadow;
  w.Element.prototype.attachShadow = function(options) {const root = attach.call(this,options);roots.set(this,root);return root;};
  const main = w.document.querySelector('main');
  function cell(id) { const el = w.document.createElement('div');el.dataset.testid = 'cellInnerDiv';el.innerHTML = `<article data-testid="tweet"><a href="/u/status/${id}"><time>今天</time></a></article>`;return el; }
  main.append(...Array.from({length:20},(_,i) => cell(i+1)));
  w.eval(await readFile('.output/chrome-mv3/content-scripts/feed.js','utf8'));
  const frame = () => new Promise(resolve => setTimeout(resolve,50)); await frame();
  const cards = () => [...w.document.querySelectorAll('x-learning-card')];
  assert.deepEqual(cards().map(c => c.dataset.anchor),['10','20']);
  const root = roots.get(cards()[0]); const [toggle] = root.querySelectorAll('button');
  toggle.click(); assert.equal(toggle.getAttribute('aria-expanded'),'true');
  toggle.click(); assert.equal(toggle.getAttribute('aria-expanded'),'false');
  assert.equal(w.attacked,undefined); assert.equal(root.querySelectorAll('script,img').length,0);
  main.append(...Array.from({length:30},(_,i) => cell(i+21))); await frame();
  assert.deepEqual(cards().map(c => c.dataset.anchor),['10','20','30']);
  main.replaceChildren(...Array.from({length:50},(_,i) => cell(i+1))); await frame();
  assert.deepEqual(cards().map(c => c.dataset.anchor),['10','20','30']);
  const before = callbacks; await frame(); assert.equal(callbacks,before);
  assert.ok(callbacks < 10,`observer callbacks: ${callbacks}`);
  feed = {...feed,settings:{every:10,enabled:false}}; refresh(); await frame(); assert.equal(cards().length,0);
  feed = {...feed,settings:{every:10,enabled:true}}; refresh(); await frame(); assert.equal(cards().length,3);
  delete w.chrome.runtime.id; refresh(); await frame(); assert.equal(cards().length,0);
  assert.deepEqual(errors,[]);
});

test('构建后的卡片：展开、复习与归档，写回失败可重试，归档立即移除',async t=>{
  const dom=new JSDOM('<main data-testid="primaryColumn"><div data-testid="cellInnerDiv"><article data-testid="tweet"><a href="/u/status/1"><time>今天</time></a></article></div></main>',{url:'https://x.com/home',runScripts:'dangerously',pretendToBeVisual:true});
  t.after(()=>dom.window.close());const w=dom.window;let refresh;const sent=[];
  w.setInterval=callback=>{refresh=callback;return 1;};w.clearInterval=()=>{};
  let feed={notes:[{id:'a'.repeat(64),source:'b'.repeat(64),title:'Obsidian 文章',html:'<p>正文</p>',metadata:{reviewCount:2,lastReviewed:'2026-10-07T09:20:33.123Z',remarks:'原备注',version:'c'.repeat(64)}}],settings:{every:1,enabled:true},version:'one'};
  let failArchive=true;
  w.chrome={runtime:{id:'test',onMessage:{addListener:()=>{},removeListener:()=>{}},getURL:path=>`chrome-extension://test${path}`,sendMessage:async message=>{if(message.type==='feed')return feed;sent.push(message);if(message.type==='archive' && failArchive){failArchive=false;return{error:'未连接，请重试'};}return{ok:true,pending:true};}}};
  const roots=new WeakMap();const attach=w.Element.prototype.attachShadow;
  w.Element.prototype.attachShadow=function(options){const root=attach.call(this,options);roots.set(this,root);return root;};
  w.eval(await readFile('.output/chrome-mv3/content-scripts/feed.js','utf8'));
  const frame=()=>new Promise(resolve=>setTimeout(resolve,50));await frame();
  const root=()=>roots.get(w.document.querySelector('x-learning-card'));
  [...root().querySelectorAll('button')].find(b=>b.textContent==='已复习 +1').click();await frame();
  assert.equal(sent[0].type,'review');assert.equal(sent[0].noteId,'a'.repeat(64));assert.equal(sent[0].metadata,undefined);
  assert.deepEqual([...root().querySelectorAll('button')].map(b=>b.textContent),['展开','已复习 +1','归档']);
  assert.equal(root().querySelector('form,input,textarea'),null);
  root().querySelector('button').click();
  feed={...feed,notes:[{...feed.notes[0],metadata:{...feed.notes[0].metadata,reviewCount:3,version:'d'.repeat(64)}}],version:'two'};
  refresh();await frame();
  assert.ok(root().querySelector('.summary').textContent.includes('已复习 3 次'));
  assert.equal(root().querySelector('button').textContent,'收起');
  assert.deepEqual([...root().querySelectorAll('button')].map(b=>b.textContent),['收起','已复习 +1','归档']);
  assert.equal(sent.length,1);
  assert.ok(!('html' in sent[0]) && !('body' in sent[0]));
  const archive=()=>[...root().querySelectorAll('button')].find(b=>b.textContent==='归档');
  archive().click();await frame();assert.ok(root());assert.equal(archive().disabled,false);
  assert.ok(root().querySelector('[role=status]').textContent.includes('未连接'));
  archive().click();await frame();assert.equal(w.document.querySelector('x-learning-card'),null);
  assert.equal(sent[2].type,'archive');assert.equal(sent[2].noteId,'a'.repeat(64));
  refresh();await frame();assert.equal(w.document.querySelector('x-learning-card'),null);
});
